#!/usr/bin/env ruby
# frozen_string_literal: true

# usage: file2qr < input

require "base64"
require "zlib"
require "fileutils"
require "json"

def self.installed?(util)
  ENV["PATH"].split(File::PATH_SEPARATOR).any? do |path|
    File.executable?(File.join(path, util))
  end
end

def info(msg, level: 0)
  indent = "    " * level
  STDERR.puts "#{indent}[+] #{msg}"
end

def die(msg)
  info msg
  exit 1
end

def qrencode(data, frameno, svg: false)
  png = File.join QR_DIR, "frame#{"%06d" % frameno}.png"

  if svg
    svg = File.join QR_DIR, "frame#{"%06d" % frameno}.svg"
    system "qrencode", "-o", svg, "-t", "svg", "-d", "144", "-s", "6", data
    system "convert", "-density", "500", "-resize", "846x846", svg, png
    FileUtils.rm_f svg
  else
    system "qrencode", "-o", png, "-t", "png", "-d", "144", "-s", "6", data
  end
end

DEPS = %w[qrencode convert].freeze

DEPS.each { |dep| die "Missing #{dep}" unless installed?(dep) }

QR_DIR = ENV["DIR"] || "qr"

FileUtils.mkdir_p QR_DIR

input = Zlib.deflate STDIN.read

frameno = 2

until input.empty?
  chunk = Base64.encode64 input.slice!(0, 512)

  info "encoding frame #{frameno}..."
  qrencode chunk, frameno

  frameno += 1
end

# write control frame as frame0.png

control_data = {
  framecount: frameno - 1,
}

info "encoding control frame..."
qrencode control_data.to_json, 1, svg: true
